import React, { useState } from 'react';
import { api } from '../../api/client';
import { Globe2, Search, Swords } from 'lucide-react';

export function PlayerComparePage() {
  const [a, setA] = useState(''); const [b, setB] = useState('');
  const [result, setResult] = useState<import('../../api/client').ApiReadResult<{ platform: Array<{ user_id: number; username: string; osu_id: string; avatar_url: string | null; global_rank: number | null; dzpp: number; rounds: number; wins: number; best: number | null }>; osu: Array<{ id: number; username: string; country: string; avatarUrl: string; globalRank: number | null }> }> | null>(null);
  const [busy, setBusy] = useState(false);
  const compare = async () => { if (!a.trim() || !b.trim()) return; setBusy(true); setResult(await api.platform.compare(a.trim(), b.trim())); setBusy(false); };
  return <div className="max-w-5xl mx-auto px-6 py-8 pb-16">
    <div className="mb-8 border-b border-slate-800/80 pb-6"><div className="flex items-center gap-3"><Swords className="h-5 w-5 text-amber-400"/><div><p className="text-[9px] uppercase tracking-[0.22em] text-amber-400/70 font-mono">Competitive tools</p><h1 className="text-2xl font-black text-white mt-1">Player comparison</h1></div></div><p className="text-sm text-slate-500 mt-3 max-w-2xl">Compare osu!DZ career results with the current public osu! profile snapshot. Values are shown side by side without a calculated winner.</p></div>
    <div className="grid md:grid-cols-[1fr_1fr_auto] gap-2 mb-8"><input value={a} onChange={(e) => setA(e.target.value)} placeholder="Player one" className="h-11 bg-[#0c1424] border border-slate-800 px-4 text-sm text-white outline-none focus:border-amber-400/50"/><input value={b} onChange={(e) => setB(e.target.value)} placeholder="Player two" className="h-11 bg-[#0c1424] border border-slate-800 px-4 text-sm text-white outline-none focus:border-amber-400/50"/><button onClick={() => void compare()} disabled={busy} className="h-11 bg-amber-400 px-5 text-xs font-black text-slate-950 hover:bg-amber-300 disabled:opacity-40"><Search className="w-3.5 h-3.5 inline mr-2"/>{busy ? 'Loading…' : 'Compare'}</button></div>
    {result?.ok && <div className="space-y-8">
      <ComparisonSection title="osu!DZ career"><div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-800/80 border-y border-slate-800/80">{result.data.platform.map((p) => <section key={p.user_id} className="py-5 md:px-6 first:pl-0 last:pr-0"><p className="text-xl font-black text-white">{p.username}</p><p className="text-[9px] font-mono uppercase tracking-wider text-slate-600 mt-1">{p.osu_id}</p><div className="grid grid-cols-2 gap-y-5 mt-6"><Metric label="DZPP" value={p.dzpp.toLocaleString()}/><Metric label="Player ID" value={p.user_id}/><Metric label="Rounds" value={p.rounds}/><Metric label="Wins" value={p.wins}/><Metric label="Best placement" value={p.best ? ' #' + p.best : '—'}/></div></section>)}</div></ComparisonSection>
      <ComparisonSection title="osu! profile"><div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-800/80 border-y border-slate-800/80">{result.data.osu.map((p) => <section key={p.id} className="py-5 md:px-6 first:pl-0 last:pr-0"><div className="flex items-center gap-3"><img src={p.avatarUrl} alt="" className="h-10 w-10 rounded-full object-cover"/><div><p className="font-black text-white">{p.username}</p><p className="text-[10px] text-slate-600 font-mono">{p.country}</p></div></div><div className="mt-6"><Metric label="Global rank" value={p.globalRank?.toLocaleString() ?? 'Unranked'}/></div></section>)}</div></ComparisonSection>
    </div>}
    {!result && <div className="border-y border-slate-800/80 py-16 text-center"><Swords className="h-7 w-7 mx-auto mb-3 text-slate-700"/><p className="text-sm text-slate-500">Enter two osu! usernames to compare their careers.</p></div>}
    {result && !result.ok && <p className="text-sm text-rose-400">{result.error}</p>}
  </div>;
}
function ComparisonSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><div className="mb-3"><p className="text-[9px] uppercase tracking-[0.22em] text-slate-600 font-mono">{title}</p></div>{children}</section>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><p className="text-[9px] uppercase tracking-widest text-slate-600 font-mono">{label}</p><p className="text-xl font-black text-white mt-1">{value}</p></div>; }
